var data = {
    "airports": [
       {
           "fs": "BBA",
           "iata": "BBA",
           "icao": "SCBA",
           "name": "Teniente Vidal Airport",
           "city": "Balmaceda",
           "cityCode": "BBA",
           "countryCode": "CL",
           "countryName": "Chile",
           "regionName": "South America",
           "timeZoneRegionName": "America/Santiago",
           "localTime": "2016-05-25T14:47:03.057",
           "utcOffsetHours": -4.0,
           "latitude": -45.916667,
           "longitude": -71.695,
           "elevationFeet": 1722,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBA?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBA?codeType=fs"
       },
       {
           "fs": "BBC",
           "iata": "BBC",
           "icao": "KBYY",
           "faa": "BYY",
           "name": "Bay City Airport",
           "city": "Bay City",
           "cityCode": "BBC",
           "stateCode": "TX",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/Chicago",
           "localTime": "2016-05-25T13:47:03.057",
           "utcOffsetHours": -5.0,
           "latitude": 28.983333,
           "longitude": -95.966667,
           "elevationFeet": 45,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBC?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBC?codeType=fs"
       },
       {
           "fs": "BBB",
           "iata": "BBB",
           "icao": "KBBB",
           "faa": "BBB",
           "name": "Benson Municipal Airport",
           "city": "Benson",
           "cityCode": "BBB",
           "stateCode": "MN",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/Chicago",
           "localTime": "2016-05-25T13:47:03.057",
           "utcOffsetHours": -5.0,
           "latitude": 45.316667,
           "longitude": -95.6,
           "elevationFeet": 1039,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBB?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBB?codeType=fs"
       },
       {
           "fs": "BBE",
           "iata": "BBE",
           "name": "Big Bell Airport",
           "city": "Big Bell",
           "cityCode": "BBE",
           "stateCode": "WA",
           "countryCode": "AU",
           "countryName": "Australia",
           "regionName": "Oceania",
           "timeZoneRegionName": "Australia/Perth",
           "localTime": "2016-05-26T02:47:03.057",
           "utcOffsetHours": 8.0,
           "latitude": -17.333333,
           "longitude": 117.583333,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBE?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBE?codeType=fs"
       },
       {
           "fs": "BBD",
           "iata": "BBD",
           "icao": "KBBD",
           "faa": "BBD",
           "name": "Curtis Field",
           "city": "Brady",
           "cityCode": "BBD",
           "stateCode": "TX",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/Chicago",
           "localTime": "2016-05-25T13:47:03.057",
           "utcOffsetHours": -5.0,
           "latitude": 31.133333,
           "longitude": -99.333333,
           "elevationFeet": 1827,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBD?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBD?codeType=fs"
       },
       {
           "fs": "EKHG",
           "icao": "EKHG",
           "name": "Herning",
           "city": "Herning",
           "countryCode": "DK",
           "countryName": "Denmark",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/Copenhagen",
           "localTime": "2016-05-25T20:47:03.057",
           "utcOffsetHours": 2.0,
           "latitude": 56.197222,
           "longitude": 9.147222,
           "elevationFeet": 167,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/EKHG?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/EKHG?codeType=fs"
       },
       {
           "fs": "BBG",
           "iata": "BBG",
           "icao": "NGTU",
           "name": "Butaritari Airport",
           "city": "Butaritari",
           "cityCode": "BBG",
           "countryCode": "KI",
           "countryName": "Kiribati",
           "regionName": "Oceania",
           "timeZoneRegionName": "Pacific/Tarawa",
           "localTime": "2016-05-26T06:47:03.057",
           "utcOffsetHours": 12.0,
           "latitude": 3.166667,
           "longitude": 172.75,
           "elevationFeet": 5,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBG?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBG?codeType=fs"
       },
       {
           "fs": "BBF",
           "iata": "BBF",
           "name": "Burlington Airport",
           "city": "Burlington",
           "cityCode": "BBF",
           "stateCode": "MA",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/New_York",
           "localTime": "2016-05-25T14:47:03.057",
           "utcOffsetHours": -4.0,
           "latitude": 42.5,
           "longitude": -71.183333,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBF?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBF?codeType=fs"
       },
       {
           "fs": "BBI",
           "iata": "BBI",
           "icao": "VEBS",
           "name": "Biju Patnaik International Airport",
           "city": "Bhubaneswar",
           "cityCode": "BBI",
           "countryCode": "IN",
           "countryName": "India",
           "regionName": "Asia",
           "timeZoneRegionName": "Asia/Kolkata",
           "localTime": "2016-05-26T00:17:03.057",
           "utcOffsetHours": 5.5,
           "latitude": 20.252853,
           "longitude": 85.817385,
           "elevationFeet": 146,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBI?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBI?codeType=fs"
       },
       {
           "fs": "GQNM",
           "icao": "GQNM",
           "name": "Dahara",
           "city": "Timbedra",
           "countryCode": "MR",
           "countryName": "Mauritania",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Nouakchott",
           "localTime": "2016-05-25T18:47:03.057",
           "utcOffsetHours": 0.0,
           "latitude": 16.3,
           "longitude": -8.05,
           "elevationFeet": 722,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/GQNM?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/GQNM?codeType=fs"
       },
       {
           "fs": "BBH",
           "iata": "BBH",
           "icao": "EDBH",
           "name": "Barth Airport",
           "city": "Barth",
           "cityCode": "BBH",
           "countryCode": "DE",
           "countryName": "Germany",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/Berlin",
           "localTime": "2016-05-25T20:47:03.057",
           "utcOffsetHours": 2.0,
           "latitude": 54.339722,
           "longitude": 12.711667,
           "elevationFeet": 22,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBH?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBH?codeType=fs"
       },
       {
           "fs": "EKHK",
           "icao": "EKHK",
           "name": "Ny Hagested",
           "city": "Holbaek",
           "countryCode": "DK",
           "countryName": "Denmark",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/Copenhagen",
           "localTime": "2016-05-25T20:47:03.057",
           "utcOffsetHours": 2.0,
           "latitude": 55.877778,
           "longitude": 11.627778,
           "elevationFeet": 27,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/EKHK?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/EKHK?codeType=fs"
       },
       {
           "fs": "BBK",
           "iata": "BBK",
           "icao": "FBKE",
           "name": "Kasane Airport",
           "city": "Kasane",
           "cityCode": "BBK",
           "countryCode": "BW",
           "countryName": "Botswana",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Gaborone",
           "localTime": "2016-05-25T20:47:03.057",
           "utcOffsetHours": 2.0,
           "latitude": -17.816667,
           "longitude": 25.15,
           "elevationFeet": 3289,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBK?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBK?codeType=fs"
       },
       {
           "fs": "BBJ",
           "iata": "BBJ",
           "name": "Bitburg Air Base",
           "city": "Bitburg",
           "cityCode": "BBJ",
           "countryCode": "DE",
           "countryName": "Germany",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/Berlin",
           "localTime": "2016-05-25T20:47:03.057",
           "utcOffsetHours": 2.0,
           "latitude": 49.966667,
           "longitude": 6.516667,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBJ?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBJ?codeType=fs"
       },
       {
           "fs": "CEB4",
           "icao": "CEB4",
           "name": "Kaybob South",
           "city": "Kaybob South",
           "stateCode": "AB",
           "countryCode": "CA",
           "countryName": "Canada",
           "regionName": "North America",
           "timeZoneRegionName": "America/Edmonton",
           "localTime": "2016-05-25T12:47:03.057",
           "utcOffsetHours": -6.0,
           "latitude": 54.236111,
           "longitude": -116.669444,
           "elevationFeet": 3290,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/CEB4?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/CEB4?codeType=fs"
       },
       {
           "fs": "BBM",
           "iata": "BBM",
           "icao": "VDGB",
           "name": "Battambang Airport",
           "city": "Battambang",
           "cityCode": "BBM",
           "countryCode": "KH",
           "countryName": "Cambodia",
           "regionName": "Asia",
           "timeZoneRegionName": "Asia/Phnom_Penh",
           "localTime": "2016-05-26T01:47:03.057",
           "utcOffsetHours": 7.0,
           "latitude": 13.116667,
           "longitude": 103.2,
           "elevationFeet": 59,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBM?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBM?codeType=fs"
       },
       {
           "fs": "BBO",
           "iata": "BBO",
           "icao": "HCMI",
           "name": "Berbera Airport",
           "city": "Berbera",
           "cityCode": "BBO",
           "countryCode": "SO",
           "countryName": "Somalia",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Mogadishu",
           "localTime": "2016-05-25T21:47:03.057",
           "utcOffsetHours": 3.0,
           "latitude": 10.419444,
           "longitude": 45.006389,
           "elevationFeet": 30,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBO?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBO?codeType=fs"
       },
       {
           "fs": "BBN",
           "iata": "BBN",
           "icao": "WBGZ",
           "name": "Bario Airport",
           "city": "Bario",
           "cityCode": "BBN",
           "countryCode": "MY",
           "countryName": "Malaysia",
           "regionName": "Asia",
           "timeZoneRegionName": "Asia/Kuala_Lumpur",
           "localTime": "2016-05-26T02:47:03.057",
           "utcOffsetHours": 8.0,
           "latitude": 3.683333,
           "longitude": 115.466667,
           "elevationFeet": 3450,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBN?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBN?codeType=fs"
       },
       {
           "fs": "BBQ",
           "iata": "BBQ",
           "icao": "TAPH",
           "name": "Barbuda Codrington Airport",
           "city": "Barbuda",
           "cityCode": "BBQ",
           "countryCode": "AG",
           "countryName": "Antigua and Barbuda",
           "regionName": "Caribbean",
           "timeZoneRegionName": "America/Antigua",
           "localTime": "2016-05-25T14:47:03.057",
           "utcOffsetHours": -4.0,
           "latitude": 17.636433,
           "longitude": -61.826681,
           "elevationFeet": 23,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBQ?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBQ?codeType=fs"
       },
       {
           "fs": "BBP",
           "iata": "BBP",
           "icao": "EGHJ",
           "name": "Bembridge Airport",
           "city": "Bembridge",
           "cityCode": "BBP",
           "stateCode": "EN",
           "countryCode": "GB",
           "countryName": "United Kingdom",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/London",
           "localTime": "2016-05-25T19:47:03.057",
           "utcOffsetHours": 1.0,
           "latitude": 50.683333,
           "longitude": -1.083333,
           "elevationFeet": 146,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBP?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBP?codeType=fs"
       },
       {
           "fs": "EKHS",
           "icao": "EKHS",
           "name": "Hadsund",
           "city": "Hadsund",
           "countryCode": "DK",
           "countryName": "Denmark",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/Copenhagen",
           "localTime": "2016-05-25T20:47:03.057",
           "utcOffsetHours": 2.0,
           "latitude": 56.811111,
           "longitude": 10.338889,
           "elevationFeet": 7,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/EKHS?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/EKHS?codeType=fs"
       },
       {
           "fs": "BBS",
           "iata": "BBS",
           "icao": "EGLK",
           "name": "Blackbush Airport",
           "city": "Blackbush",
           "cityCode": "BBS",
           "stateCode": "EN",
           "countryCode": "GB",
           "countryName": "United Kingdom",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/London",
           "localTime": "2016-05-25T19:47:03.057",
           "utcOffsetHours": 1.0,
           "latitude": 51.333333,
           "longitude": -0.85,
           "elevationFeet": 329,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBS?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBS?codeType=fs"
       },
       {
           "fs": "BBR",
           "iata": "BBR",
           "icao": "TFFB",
           "name": "Baillif Airport",
           "city": "Basse Terre",
           "cityCode": "BBR",
           "countryCode": "GP",
           "countryName": "Guadeloupe",
           "regionName": "Caribbean",
           "timeZoneRegionName": "America/Guadeloupe",
           "localTime": "2016-05-25T14:47:03.058",
           "utcOffsetHours": -4.0,
           "latitude": 16.016389,
           "longitude": -61.739444,
           "elevationFeet": 59,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBR?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBR?codeType=fs"
       },
       {
           "fs": "BBU",
           "iata": "BBU",
           "icao": "LRBS",
           "name": "Baneasa Airport",
           "city": "Bucharest",
           "cityCode": "BUH",
           "countryCode": "RO",
           "countryName": "Romania",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/Bucharest",
           "localTime": "2016-05-25T21:47:03.058",
           "utcOffsetHours": 3.0,
           "latitude": 44.495932,
           "longitude": 26.080995,
           "elevationFeet": 295,
           "classification": 3,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBU?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBU?codeType=fs"
       },
       {
           "fs": "EKHV",
           "icao": "EKHV",
           "name": "Haderslev",
           "city": "Haderslev",
           "countryCode": "DK",
           "countryName": "Denmark",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/Copenhagen",
           "localTime": "2016-05-25T20:47:03.058",
           "utcOffsetHours": 2.0,
           "latitude": 55.322222,
           "longitude": 9.575,
           "elevationFeet": 81,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/EKHV?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/EKHV?codeType=fs"
       },
       {
           "fs": "BBT",
           "iata": "BBT",
           "icao": "FEFT",
           "name": "Berberati Airport",
           "city": "Berberati",
           "cityCode": "BBT",
           "countryCode": "CF",
           "countryName": "Central African Republic",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Bangui",
           "localTime": "2016-05-25T19:47:03.058",
           "utcOffsetHours": 1.0,
           "latitude": 4.219167,
           "longitude": 15.788056,
           "elevationFeet": 1929,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBT?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBT?codeType=fs"
       },
       {
           "fs": "BBW",
           "iata": "BBW",
           "icao": "KBBW",
           "faa": "BBW",
           "name": "Broken Bow Municipal Airport",
           "city": "Broken Bow",
           "cityCode": "BBW",
           "stateCode": "NE",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/Chicago",
           "localTime": "2016-05-25T13:47:03.058",
           "utcOffsetHours": -5.0,
           "latitude": 41.431867,
           "longitude": -99.638354,
           "elevationFeet": 2526,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBW?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBW?codeType=fs"
       },
       {
           "fs": "BBV",
           "iata": "BBV",
           "icao": "DIGN",
           "name": "Bereby Airport",
           "city": "Bereby",
           "cityCode": "BBV",
           "countryCode": "CI",
           "countryName": "Cote d'Ivoire",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Abidjan",
           "localTime": "2016-05-25T18:47:03.058",
           "utcOffsetHours": 0.0,
           "latitude": 4.666667,
           "longitude": -6.95,
           "elevationFeet": 20,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBV?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBV?codeType=fs"
       },
       {
           "fs": "BBY",
           "iata": "BBY",
           "icao": "FEFM",
           "name": "Bambari Airport",
           "city": "Bambari",
           "cityCode": "BBY",
           "countryCode": "CF",
           "countryName": "Central African Republic",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Bangui",
           "localTime": "2016-05-25T19:47:03.058",
           "utcOffsetHours": 1.0,
           "latitude": 5.845833,
           "longitude": 20.649722,
           "elevationFeet": 1549,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBY?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBY?codeType=fs"
       },
       {
           "fs": "BBX",
           "iata": "BBX",
           "name": "Wings Field",
           "city": "Blue Bell",
           "cityCode": "BBX",
           "stateCode": "PA",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/New_York",
           "localTime": "2016-05-25T14:47:03.058",
           "utcOffsetHours": -4.0,
           "latitude": 40.136667,
           "longitude": -75.2675,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBX?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBX?codeType=fs"
       },
       {
           "fs": "BBZ",
           "iata": "BBZ",
           "icao": "FLZB",
           "name": "Zambezi Airport",
           "city": "Zambezi",
           "cityCode": "BBZ",
           "countryCode": "ZM",
           "countryName": "Zambia",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Lusaka",
           "localTime": "2016-05-25T20:47:03.058",
           "utcOffsetHours": 2.0,
           "latitude": -13.537222,
           "longitude": 23.11,
           "elevationFeet": 3540,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BBZ?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BBZ?codeType=fs"
       },
       {
           "fs": "FNLB",
           "icao": "FNLB",
           "name": "Lobito",
           "city": "Lobito",
           "countryCode": "AO",
           "countryName": "Angola",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Luanda",
           "localTime": "2016-05-25T19:47:03.058",
           "utcOffsetHours": 1.0,
           "latitude": -12.366667,
           "longitude": 13.533333,
           "elevationFeet": 10,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/FNLB?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/FNLB?codeType=fs"
       },
       {
           "fs": "BCB",
           "iata": "BCB",
           "icao": "KBCB",
           "faa": "BCB",
           "name": "Virginia Tech Airport",
           "city": "Blacksburg",
           "cityCode": "BCB",
           "stateCode": "VA",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/New_York",
           "localTime": "2016-05-25T14:47:03.058",
           "utcOffsetHours": -4.0,
           "latitude": 37.233333,
           "longitude": -80.416667,
           "elevationFeet": 2132,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCB?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCB?codeType=fs"
       },
       {
           "fs": "BCA",
           "iata": "BCA",
           "icao": "MUBA",
           "name": "Baracoa Airport",
           "city": "Baracoa",
           "cityCode": "BCA",
           "countryCode": "CU",
           "countryName": "Cuba",
           "regionName": "Caribbean",
           "timeZoneRegionName": "America/Havana",
           "localTime": "2016-05-25T14:47:03.058",
           "utcOffsetHours": -4.0,
           "latitude": 20.35,
           "longitude": -74.5,
           "elevationFeet": 33,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCA?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCA?codeType=fs"
       },
       {
           "fs": "BCD",
           "iata": "BCD",
           "icao": "RPVB",
           "name": "Bacolod-Silay International Airport",
           "city": "Bacolod",
           "cityCode": "BCD",
           "countryCode": "PH",
           "countryName": "Philippines",
           "regionName": "Asia",
           "timeZoneRegionName": "Asia/Manila",
           "localTime": "2016-05-26T02:47:03.058",
           "utcOffsetHours": 8.0,
           "latitude": 10.644815,
           "longitude": 122.933593,
           "elevationFeet": 20,
           "classification": 3,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCD?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCD?codeType=fs"
       },
       {
           "fs": "BCC",
           "iata": "BCC",
           "name": "Bear Creek Airport",
           "city": "Bear Creek",
           "cityCode": "BCC",
           "stateCode": "AK",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/Anchorage",
           "localTime": "2016-05-25T10:47:03.058",
           "utcOffsetHours": -8.0,
           "latitude": 45.183333,
           "longitude": -109.1,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCC?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCC?codeType=fs"
       },
       {
           "fs": "BCF",
           "iata": "BCF",
           "name": "Bouca Airport",
           "city": "Bouca",
           "cityCode": "BCF",
           "countryCode": "CF",
           "countryName": "Central African Republic",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Bangui",
           "localTime": "2016-05-25T19:47:03.058",
           "utcOffsetHours": 1.0,
           "latitude": 6.75,
           "longitude": 18.416667,
           "elevationFeet": 1532,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCF?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCF?codeType=fs"
       },
       {
           "fs": "BCE",
           "iata": "BCE",
           "icao": "KBCE",
           "faa": "BCE",
           "name": "Bryce Airport",
           "city": "Bryce",
           "cityCode": "BCE",
           "stateCode": "UT",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/Denver",
           "localTime": "2016-05-25T12:47:03.058",
           "utcOffsetHours": -6.0,
           "latitude": 37.701111,
           "longitude": -112.135278,
           "elevationFeet": 7586,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCE?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCE?codeType=fs"
       },
       {
           "fs": "BCH",
           "iata": "BCH",
           "icao": "WPEC",
           "name": "Baucau Airport",
           "city": "Baucau",
           "cityCode": "BCH",
           "countryCode": "ID",
           "countryName": "Indonesia",
           "regionName": "Asia",
           "timeZoneRegionName": "Asia/Jayapura",
           "localTime": "2016-05-26T03:47:03.058",
           "utcOffsetHours": 9.0,
           "latitude": -8.480239,
           "longitude": 126.396437,
           "elevationFeet": 1722,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCH?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCH?codeType=fs"
       },
       {
           "fs": "BCG",
           "iata": "BCG",
           "name": "Bemichi Airport",
           "city": "Bemichi",
           "cityCode": "BCG",
           "countryCode": "GY",
           "countryName": "Guyana",
           "regionName": "South America",
           "timeZoneRegionName": "America/Guyana",
           "localTime": "2016-05-25T14:47:03.058",
           "utcOffsetHours": -4.0,
           "latitude": 6.55,
           "longitude": -58.55,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCG?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCG?codeType=fs"
       },
       {
           "fs": "EKGH",
           "icao": "EKGH",
           "name": "Gronholt",
           "city": "Gronholt",
           "countryCode": "DK",
           "countryName": "Denmark",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/Copenhagen",
           "localTime": "2016-05-25T20:47:03.058",
           "utcOffsetHours": 2.0,
           "latitude": 55.997222,
           "longitude": 12.519444,
           "elevationFeet": 97,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/EKGH?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/EKGH?codeType=fs"
       },
       {
           "fs": "BCJ",
           "iata": "BCJ",
           "name": "Baca Grande Airport",
           "city": "Baca Grande",
           "cityCode": "BCJ",
           "stateCode": "CO",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/Denver",
           "localTime": "2016-05-25T12:47:03.058",
           "utcOffsetHours": -6.0,
           "latitude": 39.0,
           "longitude": -106.0,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCJ?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCJ?codeType=fs"
       },
       {
           "fs": "BCI",
           "iata": "BCI",
           "icao": "YBAR",
           "name": "Barcaldine Airport",
           "city": "Barcaldine",
           "cityCode": "BCI",
           "stateCode": "QLD",
           "countryCode": "AU",
           "countryName": "Australia",
           "regionName": "Oceania",
           "timeZoneRegionName": "Australia/Brisbane",
           "localTime": "2016-05-26T04:47:03.058",
           "utcOffsetHours": 10.0,
           "latitude": -23.559167,
           "longitude": 145.301944,
           "elevationFeet": 878,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCI?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCI?codeType=fs"
       },
       {
           "fs": "BCL",
           "iata": "BCL",
           "icao": "MRBC",
           "name": "Barra del Colorado Airport",
           "city": "Barra del Colorado",
           "cityCode": "BCL",
           "countryCode": "CR",
           "countryName": "Costa Rica",
           "regionName": "Central America",
           "timeZoneRegionName": "America/Costa_Rica",
           "localTime": "2016-05-25T12:47:03.058",
           "utcOffsetHours": -6.0,
           "latitude": 10.771923,
           "longitude": -83.586633,
           "elevationFeet": 19,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCL?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCL?codeType=fs"
       },
       {
           "fs": "BCK",
           "iata": "BCK",
           "name": "Bolwarra Airport",
           "city": "Bolwarra",
           "cityCode": "BCK",
           "stateCode": "QLD",
           "countryCode": "AU",
           "countryName": "Australia",
           "regionName": "Oceania",
           "timeZoneRegionName": "Australia/Brisbane",
           "localTime": "2016-05-26T04:47:03.058",
           "utcOffsetHours": 10.0,
           "latitude": -17.4,
           "longitude": 144.166667,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCK?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCK?codeType=fs"
       },
       {
           "fs": "BCN",
           "iata": "BCN",
           "icao": "LEBL",
           "name": "Barcelona-El Prat Airport",
           "city": "Barcelona",
           "cityCode": "BCN",
           "stateCode": "SP",
           "countryCode": "ES",
           "countryName": "Spain and Canary Islands",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/Madrid",
           "localTime": "2016-05-25T20:47:03.058",
           "utcOffsetHours": 2.0,
           "latitude": 41.303027,
           "longitude": 2.07593,
           "elevationFeet": 13,
           "classification": 1,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCN?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCN?codeType=fs"
       },
       {
           "fs": "BCM",
           "iata": "BCM",
           "icao": "LRBC",
           "name": "Bacau Airport",
           "city": "Bacau",
           "cityCode": "BCM",
           "countryCode": "RO",
           "countryName": "Romania",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/Bucharest",
           "localTime": "2016-05-25T21:47:03.058",
           "utcOffsetHours": 3.0,
           "latitude": 46.598611,
           "longitude": 26.881944,
           "elevationFeet": 607,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCM?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCM?codeType=fs"
       },
       {
           "fs": "CEC3",
           "icao": "CEC3",
           "name": "Fox Lake",
           "city": "Fox Lake",
           "stateCode": "AB",
           "countryCode": "CA",
           "countryName": "Canada",
           "regionName": "North America",
           "timeZoneRegionName": "America/Edmonton",
           "localTime": "2016-05-25T12:47:03.058",
           "utcOffsetHours": -6.0,
           "latitude": 58.533333,
           "longitude": -114.627778,
           "elevationFeet": 850,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/CEC3?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/CEC3?codeType=fs"
       },
       {
           "fs": "BCP",
           "iata": "BCP",
           "name": "Bambu Airport",
           "city": "Bambu",
           "cityCode": "BCP",
           "countryCode": "PG",
           "countryName": "Papua New Guinea",
           "regionName": "Asia",
           "timeZoneRegionName": "Pacific/Port_Moresby",
           "localTime": "2016-05-26T04:47:03.059",
           "utcOffsetHours": 10.0,
           "latitude": -5.85,
           "longitude": 146.483333,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCP?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCP?codeType=fs"
       },
       {
           "fs": "BCO",
           "iata": "BCO",
           "icao": "HABC",
           "name": "Jinka Airport",
           "city": "Jinka",
           "cityCode": "BCO",
           "countryCode": "ET",
           "countryName": "Ethiopia",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Addis_Ababa",
           "localTime": "2016-05-25T21:47:03.059",
           "utcOffsetHours": 3.0,
           "latitude": 5.783333,
           "longitude": 36.55,
           "elevationFeet": 4300,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCO?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCO?codeType=fs"
       },
       {
           "fs": "BCR",
           "iata": "BCR",
           "name": "Boca Do Acre Airport",
           "city": "Boca Do Acre",
           "cityCode": "BCR",
           "stateCode": "AM",
           "countryCode": "BR",
           "countryName": "Brazil",
           "regionName": "South America",
           "timeZoneRegionName": "America/Porto_Velho",
           "localTime": "2016-05-25T14:47:03.059",
           "utcOffsetHours": -4.0,
           "latitude": -8.75,
           "longitude": -67.383333,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCR?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCR?codeType=fs"
       },
       {
           "fs": "BCQ",
           "iata": "BCQ",
           "name": "Brack Airport",
           "city": "Brack",
           "cityCode": "BCQ",
           "countryCode": "LY",
           "countryName": "Libya",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Tripoli",
           "localTime": "2016-05-25T20:47:03.059",
           "utcOffsetHours": 2.0,
           "latitude": 27.683333,
           "longitude": 14.216667,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCQ?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCQ?codeType=fs"
       },
       {
           "fs": "BCT",
           "iata": "BCT",
           "icao": "KBCT",
           "faa": "BCT",
           "name": "Boca Raton Airport",
           "city": "Boca Raton",
           "cityCode": "BCT",
           "stateCode": "FL",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/New_York",
           "localTime": "2016-05-25T14:47:03.059",
           "utcOffsetHours": -4.0,
           "latitude": 26.379022,
           "longitude": -80.107981,
           "elevationFeet": 9,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCT?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCT?codeType=fs"
       },
       {
           "fs": "BCS",
           "iata": "BCS",
           "name": "Southern Sea Plane Base",
           "city": "Belle Chasse",
           "cityCode": "BCS",
           "stateCode": "LA",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/Chicago",
           "localTime": "2016-05-25T13:47:03.059",
           "utcOffsetHours": -5.0,
           "latitude": 29.86594,
           "longitude": -90.020305,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCS?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCS?codeType=fs"
       },
       {
           "fs": "BCV",
           "iata": "BCV",
           "name": "Belmopan Airport",
           "city": "Belmopan",
           "cityCode": "BCV",
           "countryCode": "BZ",
           "countryName": "Belize",
           "regionName": "Central America",
           "timeZoneRegionName": "America/Belize",
           "localTime": "2016-05-25T12:47:03.059",
           "utcOffsetHours": -6.0,
           "latitude": 17.270499,
           "longitude": -88.77904,
           "elevationFeet": 197,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCV?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCV?codeType=fs"
       },
       {
           "fs": "BCU",
           "iata": "BCU",
           "name": "Bauchi Airport",
           "city": "Bauchi",
           "cityCode": "BCU",
           "countryCode": "NG",
           "countryName": "Nigeria",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Lagos",
           "localTime": "2016-05-25T19:47:03.059",
           "utcOffsetHours": 1.0,
           "latitude": 10.366667,
           "longitude": 9.8,
           "elevationFeet": 2003,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCU?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCU?codeType=fs"
       },
       {
           "fs": "BCX",
           "iata": "BCX",
           "name": "Beloreck Airport",
           "city": "Beloreck",
           "cityCode": "BCX",
           "countryCode": "RU",
           "countryName": "Russian Federation",
           "regionName": "Europe",
           "timeZoneRegionName": "Asia/Yekaterinburg",
           "localTime": "2016-05-25T23:47:03.059",
           "utcOffsetHours": 5.0,
           "latitude": 53.933333,
           "longitude": 58.333333,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCX?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCX?codeType=fs"
       },
       {
           "fs": "BCW",
           "iata": "BCW",
           "name": "Benguera Island Airport",
           "city": "Benguera Island",
           "cityCode": "BCW",
           "countryCode": "MZ",
           "countryName": "Mozambique",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Maputo",
           "localTime": "2016-05-25T20:47:03.059",
           "utcOffsetHours": 2.0,
           "latitude": -21.884722,
           "longitude": 35.425,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCW?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCW?codeType=fs"
       },
       {
           "fs": "BCZ",
           "iata": "BCZ",
           "name": "Bickerton Island Airport",
           "city": "Bickerton Island",
           "cityCode": "BCZ",
           "stateCode": "NT",
           "countryCode": "AU",
           "countryName": "Australia",
           "regionName": "Oceania",
           "timeZoneRegionName": "Australia/Darwin",
           "localTime": "2016-05-26T04:17:03.059",
           "utcOffsetHours": 9.5,
           "latitude": -13.783333,
           "longitude": 137.8,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCZ?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCZ?codeType=fs"
       },
       {
           "fs": "BCY",
           "iata": "BCY",
           "name": "Bulchi Airport",
           "city": "Bulchi",
           "cityCode": "BCY",
           "countryCode": "ET",
           "countryName": "Ethiopia",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Addis_Ababa",
           "localTime": "2016-05-25T21:47:03.059",
           "utcOffsetHours": 3.0,
           "latitude": 6.216667,
           "longitude": 36.666667,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BCY?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BCY?codeType=fs"
       },
       {
           "fs": "BDA",
           "iata": "BDA",
           "icao": "TXKF",
           "name": "L.F. Wade International Airport",
           "city": "Bermuda",
           "cityCode": "BDA",
           "countryCode": "BM",
           "countryName": "Bermuda",
           "regionName": "Caribbean",
           "timeZoneRegionName": "Atlantic/Bermuda",
           "localTime": "2016-05-25T15:47:03.059",
           "utcOffsetHours": -3.0,
           "latitude": 32.35994,
           "longitude": -64.701148,
           "elevationFeet": 12,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDA?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDA?codeType=fs"
       },
       {
           "fs": "BDC",
           "iata": "BDC",
           "icao": "SNBC",
           "name": "Barra Do Corda Airport",
           "city": "Barra Do Corda",
           "cityCode": "BDC",
           "stateCode": "MA",
           "countryCode": "BR",
           "countryName": "Brazil",
           "regionName": "South America",
           "timeZoneRegionName": "America/Belem",
           "localTime": "2016-05-25T15:47:03.059",
           "utcOffsetHours": -3.0,
           "latitude": -5.466667,
           "longitude": -45.266667,
           "elevationFeet": 509,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDC?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDC?codeType=fs"
       },
       {
           "fs": "BDB",
           "iata": "BDB",
           "icao": "YBUD",
           "name": "Bundaberg Airport",
           "city": "Bundaberg",
           "cityCode": "BDB",
           "stateCode": "QLD",
           "countryCode": "AU",
           "countryName": "Australia",
           "regionName": "Oceania",
           "timeZoneRegionName": "Australia/Brisbane",
           "localTime": "2016-05-26T04:47:03.059",
           "utcOffsetHours": 10.0,
           "latitude": -24.898709,
           "longitude": 152.321873,
           "elevationFeet": 107,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDB?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDB?codeType=fs"
       },
       {
           "fs": "BDE",
           "iata": "BDE",
           "icao": "KBDE",
           "faa": "BDE",
           "name": "Baudette Airport",
           "city": "Baudette",
           "cityCode": "BDE",
           "stateCode": "MN",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/Chicago",
           "localTime": "2016-05-25T13:47:03.059",
           "utcOffsetHours": -5.0,
           "latitude": 48.722778,
           "longitude": -94.606944,
           "elevationFeet": 1084,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDE?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDE?codeType=fs"
       },
       {
           "fs": "BDD",
           "iata": "BDD",
           "icao": "YBAU",
           "name": "Badu Island Airport",
           "city": "Badu Island",
           "cityCode": "BDD",
           "stateCode": "QLD",
           "countryCode": "AU",
           "countryName": "Australia",
           "regionName": "Oceania",
           "timeZoneRegionName": "Australia/Brisbane",
           "localTime": "2016-05-26T04:47:03.059",
           "utcOffsetHours": 10.0,
           "latitude": -10.148655,
           "longitude": 142.171657,
           "elevationFeet": 45,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDD?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDD?codeType=fs"
       },
       {
           "fs": "HTSH",
           "icao": "HTSH",
           "name": "Mafinga",
           "city": "Sao Hill",
           "countryCode": "TZ",
           "countryName": "United Republic of Tanzania",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Dar_es_Salaam",
           "localTime": "2016-05-25T21:47:03.059",
           "utcOffsetHours": 3.0,
           "latitude": -8.35,
           "longitude": 35.3,
           "elevationFeet": 6300,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/HTSH?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/HTSH?codeType=fs"
       },
       {
           "fs": "BDG",
           "iata": "BDG",
           "icao": "KBDG",
           "faa": "BDG",
           "name": "Blanding Airport",
           "city": "Blanding",
           "cityCode": "BDG",
           "stateCode": "UT",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/Denver",
           "localTime": "2016-05-25T12:47:03.059",
           "utcOffsetHours": -6.0,
           "latitude": 37.616667,
           "longitude": -109.483333,
           "elevationFeet": 5865,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDG?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDG?codeType=fs"
       },
       {
           "fs": "BDF",
           "iata": "BDF",
           "name": "Rinkenberger Airport",
           "city": "Bradford",
           "cityCode": "BDF",
           "stateCode": "IL",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/Chicago",
           "localTime": "2016-05-25T13:47:03.059",
           "utcOffsetHours": -5.0,
           "latitude": 41.183333,
           "longitude": -89.65,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDF?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDF?codeType=fs"
       },
       {
           "fs": "BDI",
           "iata": "BDI",
           "icao": "FSSB",
           "name": "Bird Island Airport",
           "city": "Bird Island",
           "cityCode": "BDI",
           "countryCode": "SC",
           "countryName": "Seychelles",
           "regionName": "Africa",
           "timeZoneRegionName": "Indian/Mahe",
           "localTime": "2016-05-25T22:47:03.059",
           "utcOffsetHours": 4.0,
           "latitude": -3.716667,
           "longitude": 55.216667,
           "elevationFeet": 6,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDI?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDI?codeType=fs"
       },
       {
           "fs": "BDH",
           "iata": "BDH",
           "icao": "OIBL",
           "name": "Bandar Lengeh Airport",
           "city": "Bandar Lengeh",
           "cityCode": "BDH",
           "countryCode": "IR",
           "countryName": "Iran",
           "regionName": "Asia",
           "timeZoneRegionName": "Asia/Tehran",
           "localTime": "2016-05-25T23:17:03.059",
           "utcOffsetHours": 4.5,
           "latitude": 26.529485,
           "longitude": 54.829146,
           "elevationFeet": 87,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDH?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDH?codeType=fs"
       },
       {
           "fs": "BDK",
           "iata": "BDK",
           "icao": "DIBU",
           "name": "Bondoukou Airport",
           "city": "Bondoukou",
           "cityCode": "BDK",
           "countryCode": "CI",
           "countryName": "Cote d'Ivoire",
           "regionName": "Africa",
           "timeZoneRegionName": "Africa/Abidjan",
           "localTime": "2016-05-25T18:47:03.059",
           "utcOffsetHours": 0.0,
           "latitude": 8.033333,
           "longitude": -2.8,
           "elevationFeet": 1207,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDK?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDK?codeType=fs"
       },
       {
           "fs": "BDJ",
           "iata": "BDJ",
           "icao": "WAOO",
           "name": "Syamsudin Noor International Airport",
           "city": "Banjarmasin",
           "cityCode": "BDJ",
           "countryCode": "ID",
           "countryName": "Indonesia",
           "regionName": "Asia",
           "timeZoneRegionName": "Asia/Makassar",
           "localTime": "2016-05-26T02:47:03.059",
           "utcOffsetHours": 8.0,
           "latitude": -3.43804,
           "longitude": 114.754253,
           "elevationFeet": 66,
           "classification": 3,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDJ?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDJ?codeType=fs"
       },
       {
           "fs": "BDM",
           "iata": "BDM",
           "icao": "LTBG",
           "name": "Bandirma Airport",
           "city": "Bandirma",
           "cityCode": "BDM",
           "countryCode": "TR",
           "countryName": "Turkey",
           "regionName": "Europe",
           "timeZoneRegionName": "Europe/Istanbul",
           "localTime": "2016-05-25T21:47:03.059",
           "utcOffsetHours": 3.0,
           "latitude": 40.318333,
           "longitude": 27.977222,
           "elevationFeet": 167,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDM?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDM?codeType=fs"
       },
       {
           "fs": "BDL",
           "iata": "BDL",
           "icao": "KBDL",
           "faa": "BDL",
           "name": "Bradley International Airport",
           "street1": "Schoephoester Road",
           "street2": "",
           "city": "Hartford",
           "cityCode": "HFD",
           "stateCode": "CT",
           "postalCode": "06096",
           "countryCode": "US",
           "countryName": "United States",
           "regionName": "North America",
           "timeZoneRegionName": "America/New_York",
           "weatherZone": "CTZ002",
           "localTime": "2016-05-25T14:47:03.059",
           "utcOffsetHours": -4.0,
           "latitude": 41.92953,
           "longitude": -72.684701,
           "elevationFeet": 173,
           "classification": 2,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDL?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDL?codeType=fs"
       },
       {
           "fs": "BDO",
           "iata": "BDO",
           "icao": "WICC",
           "name": "Husein Sastranegara Airport",
           "city": "Bandung",
           "cityCode": "BDO",
           "countryCode": "ID",
           "countryName": "Indonesia",
           "regionName": "Asia",
           "timeZoneRegionName": "Asia/Jakarta",
           "localTime": "2016-05-26T01:47:03.059",
           "utcOffsetHours": 7.0,
           "latitude": -6.904648,
           "longitude": 107.581779,
           "elevationFeet": 2430,
           "classification": 3,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDO?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDO?codeType=fs"
       },
       {
           "fs": "CED5",
           "icao": "CED5",
           "name": "Taber Airport",
           "city": "Taber",
           "stateCode": "AB",
           "countryCode": "CA",
           "countryName": "Canada",
           "regionName": "North America",
           "timeZoneRegionName": "America/Edmonton",
           "localTime": "2016-05-25T12:47:03.059",
           "utcOffsetHours": -6.0,
           "latitude": 49.827249,
           "longitude": -112.180346,
           "elevationFeet": 2632,
           "classification": 4,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/CED5?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/CED5?codeType=fs"
       },
       {
           "fs": "BDN",
           "iata": "BDN",
           "name": "Talhar Airport",
           "city": "Badin",
           "cityCode": "BDN",
           "countryCode": "PK",
           "countryName": "Pakistan",
           "regionName": "Asia",
           "timeZoneRegionName": "Asia/Karachi",
           "localTime": "2016-05-25T23:47:03.06",
           "utcOffsetHours": 5.0,
           "latitude": 24.633333,
           "longitude": 68.9,
           "elevationFeet": 0,
           "classification": 5,
           "active": true,
           "weatherUrl": "https://api.flightstats.com/flex/weather/rest/v1/json/all/BDN?codeType=fs",
           "delayIndexUrl": "https://api.flightstats.com/flex/delayindex/rest/v1/json/airports/BDN?codeType=fs"
       }
    ]
};