var data = {  
   "entries":[  
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E6 Svinesund",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"0101",
         "long":"11.25596",
         "lat":"59.10881",
         "takst_stor_bil":"100.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E6 RAUKERUD",
         "autopass":"Ja",
         "takst_liten_bil":"21.0",
         "kommunenr":"0104",
         "long":"10.70717",
         "lat":"59.48563",
         "takst_stor_bil":"42.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Hovinmoen - Dal",
         "autopass":"Ja",
         "takst_liten_bil":"19.0",
         "kommunenr":"0235",
         "long":"11.17289",
         "lat":"60.18095",
         "takst_stor_bil":"38.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Dal - Boksrud",
         "autopass":"Ja",
         "takst_liten_bil":"19.0",
         "kommunenr":"0237",
         "long":"11.14134",
         "lat":"60.30650",
         "takst_stor_bil":"38.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Boksrud - Minnesund",
         "autopass":"Ja",
         "takst_liten_bil":"15.0",
         "kommunenr":"0237",
         "long":"11.20553",
         "lat":"60.37159",
         "takst_stor_bil":"30.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Minnesund - Hedmark grense",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"0237",
         "long":"11.24076",
         "lat":"60.41898",
         "takst_stor_bil":"40.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E6 Europaveien",
         "autopass":"Ja",
         "takst_liten_bil":"32.0",
         "kommunenr":"0301",
         "long":"10.81977",
         "lat":"59.87818",
         "takst_stor_bil":"96.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Djupdalsveien",
         "autopass":"Ja",
         "takst_liten_bil":"32.0",
         "kommunenr":"0301",
         "long":"10.83034",
         "lat":"59.92365",
         "takst_stor_bil":"96.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rv 190 Ulven",
         "autopass":"Ja",
         "takst_liten_bil":"32.0",
         "kommunenr":"0301",
         "long":"10.82581",
         "lat":"59.92216",
         "takst_stor_bil":"96.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Akershus grense - Skaberud",
         "autopass":"Ja",
         "takst_liten_bil":"21.0",
         "kommunenr":"0417",
         "long":"11.25050",
         "lat":"60.55447",
         "takst_stor_bil":"42.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Skaberud - Kolomoen",
         "autopass":"Ja",
         "takst_liten_bil":"23.0",
         "kommunenr":"0417",
         "long":"11.29279",
         "lat":"60.64937",
         "takst_stor_bil":"46.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E6 Tingberg",
         "autopass":"Ja",
         "takst_liten_bil":"22.0",
         "kommunenr":"0521",
         "long":"10.39998",
         "lat":"61.27214",
         "takst_stor_bil":"44.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Klett - E6, S-snitt",
         "autopass":"Ja",
         "takst_liten_bil":"11.0",
         "kommunenr":"1601",
         "long":"10.33143",
         "lat":"63.32601",
         "takst_stor_bil":"33.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Tonstad, T-snitt",
         "autopass":"Ja",
         "takst_liten_bil":"9.0",
         "kommunenr":"1601",
         "long":"10.37943",
         "lat":"63.37183",
         "takst_stor_bil":"27.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Ranheim",
         "autopass":"Ja",
         "takst_liten_bil":"37.0",
         "kommunenr":"1601",
         "long":"10.55476",
         "lat":"63.42260",
         "takst_stor_bil":"74.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Hommelvik",
         "autopass":"Ja",
         "takst_liten_bil":"18.0",
         "kommunenr":"1663",
         "long":"10.82518",
         "lat":"63.41534",
         "takst_stor_bil":"36.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Kroppan bru (Sørgående), M-snitt",
         "autopass":"Ja",
         "takst_liten_bil":"9.0",
         "kommunenr":"1601",
         "long":"10.39352",
         "lat":"63.39818",
         "takst_stor_bil":"45.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Kroppan bru (Nordgående), M-snitt",
         "autopass":"Ja",
         "takst_liten_bil":"9.0",
         "kommunenr":"1601",
         "long":"10.39425",
         "lat":"63.39915",
         "takst_stor_bil":"45.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Leistad",
         "autopass":"Ja",
         "takst_liten_bil":"18.0",
         "kommunenr":"1663",
         "long":"10.63317",
         "lat":"63.42267",
         "takst_stor_bil":"36.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E6 Skamdal",
         "autopass":"Ja",
         "takst_liten_bil":"12.0",
         "kommunenr":"1833",
         "long":"13.88586",
         "lat":"66.23152",
         "takst_stor_bil":"36.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E6 Reinforshei",
         "autopass":"Ja",
         "takst_liten_bil":"17.0",
         "kommunenr":"1833",
         "long":"14.30851",
         "lat":"66.34104",
         "takst_stor_bil":"51.0"
      },
      {  
         "vegnr":"Ev6",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E6/E10 Leirvik",
         "autopass":"Ja",
         "takst_liten_bil":"43.0",
         "kommunenr":"1805",
         "long":"17.56709",
         "lat":"68.47472",
         "takst_stor_bil":"129.0"
      },
      {  
         "vegnr":"Ev16",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E16 Nybakk",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"0235",
         "long":"11.29976",
         "lat":"60.12256",
         "takst_stor_bil":"40.0"
      },
      {  
         "vegnr":"Ev16",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E16 Åsum",
         "autopass":"Ja",
         "takst_liten_bil":"32.0",
         "kommunenr":"0402",
         "long":"11.94041",
         "lat":"60.20683",
         "takst_stor_bil":"64.0"
      },
      {  
         "vegnr":"Ev16",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E16 Koparvike",
         "autopass":"Ja",
         "takst_liten_bil":"34.0",
         "kommunenr":"0540",
         "long":"9.61479",
         "lat":"60.78073",
         "takst_stor_bil":"68.0"
      },
      {  
         "vegnr":"Ev16",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E16 Bolstad",
         "autopass":"Ja",
         "takst_liten_bil":"43.0",
         "kommunenr":"1235",
         "long":"5.94083",
         "lat":"60.63549",
         "takst_stor_bil":"86.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 RAMSTAD",
         "autopass":"Ja",
         "takst_liten_bil":"10.0",
         "kommunenr":"0125",
         "long":"11.33346",
         "lat":"59.57673",
         "takst_stor_bil":"20.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 BRENNEMOEN",
         "autopass":"Ja",
         "takst_liten_bil":"15.0",
         "kommunenr":"0125",
         "long":"11.27564",
         "lat":"59.57636",
         "takst_stor_bil":"30.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 DALEN",
         "autopass":"Ja",
         "takst_liten_bil":"10.0",
         "kommunenr":"0123",
         "long":"11.08617",
         "lat":"59.59382",
         "takst_stor_bil":"20.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E 18 hovedløp",
         "autopass":"Ja",
         "takst_liten_bil":"16.0",
         "kommunenr":"0219",
         "long":"10.62807",
         "lat":"59.90984",
         "takst_stor_bil":"48.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rampe Lysaker til E 18",
         "autopass":"Ja",
         "takst_liten_bil":"16.0",
         "kommunenr":"0219",
         "long":"10.63324",
         "lat":"59.91154",
         "takst_stor_bil":"48.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Pårampe Granfoss fra E18",
         "autopass":"Ja",
         "takst_liten_bil":"16.0",
         "kommunenr":"0219",
         "long":"10.62833",
         "lat":"59.90971",
         "takst_stor_bil":"48.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 Mosseveien",
         "autopass":"Ja",
         "takst_liten_bil":"32.0",
         "kommunenr":"0301",
         "long":"10.76865",
         "lat":"59.88492",
         "takst_stor_bil":"96.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 Maritim",
         "autopass":"Ja",
         "takst_liten_bil":"32.0",
         "kommunenr":"0301",
         "long":"10.67267",
         "lat":"59.92050",
         "takst_stor_bil":"96.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 Påkjøringsrampe",
         "autopass":"Ja",
         "takst_liten_bil":"32.0",
         "kommunenr":"0301",
         "long":"10.67733",
         "lat":"59.92039",
         "takst_stor_bil":"96.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 Gulli",
         "autopass":"Ja",
         "takst_liten_bil":"5.0",
         "kommunenr":"0704",
         "long":"10.35878",
         "lat":"59.30284",
         "takst_stor_bil":"10.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 Ramsum",
         "autopass":"Ja",
         "takst_liten_bil":"11.0",
         "kommunenr":"0720",
         "long":"10.29947",
         "lat":"59.26191",
         "takst_stor_bil":"22.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 Fokserød",
         "autopass":"Ja",
         "takst_liten_bil":"6.0",
         "kommunenr":"0706",
         "long":"10.20764",
         "lat":"59.19077",
         "takst_stor_bil":"12.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 Natvall",
         "autopass":"Ja",
         "takst_liten_bil":"7.0",
         "kommunenr":"0706",
         "long":"10.20184",
         "lat":"59.16614",
         "takst_stor_bil":"14.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 Skinmo",
         "autopass":"Ja",
         "takst_liten_bil":"9.0",
         "kommunenr":"0709",
         "long":"10.13212",
         "lat":"59.11974",
         "takst_stor_bil":"18.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 Sky",
         "autopass":"Ja",
         "takst_liten_bil":"12.0",
         "kommunenr":"0709",
         "long":"9.94015",
         "lat":"59.07049",
         "takst_stor_bil":"24.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Østerholtheia",
         "autopass":"Ja",
         "takst_liten_bil":"30.0",
         "kommunenr":"0911",
         "long":"9.15064",
         "lat":"58.86763",
         "takst_stor_bil":"60.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Inntjore",
         "autopass":"Ja",
         "takst_liten_bil":"15.0",
         "kommunenr":"0904",
         "long":"8.46181",
         "lat":"58.29688",
         "takst_stor_bil":"30.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Kviksdalen",
         "autopass":"Ja",
         "takst_liten_bil":"15.0",
         "kommunenr":"0926",
         "long":"8.19204",
         "lat":"58.20017",
         "takst_stor_bil":"30.0"
      },
      {  
         "vegnr":"Ev18",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E18 Bjørndalsletta",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1001",
         "long":"8.02329",
         "lat":"58.16207",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Ev39",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E39 Vesterveien",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1001",
         "long":"7.97643",
         "lat":"58.14120",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Ev39",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E39 Handeland",
         "autopass":"Ja",
         "takst_liten_bil":"25.0",
         "kommunenr":"1032",
         "long":"7.01866",
         "lat":"58.21786",
         "takst_stor_bil":"50.0"
      },
      {  
         "vegnr":"Ev39",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E39 BRÅSTEIN",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"1102",
         "long":"5.79377",
         "lat":"58.79599",
         "takst_stor_bil":"50.0"
      },
      {  
         "vegnr":"Ev39",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E39 FORUS",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"1102",
         "long":"5.71662",
         "lat":"58.88898",
         "takst_stor_bil":"50.0"
      },
      {  
         "vegnr":"Ev39",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E39 RANDABERGVEIEN",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"1103",
         "long":"5.67202",
         "lat":"58.98348",
         "takst_stor_bil":"50.0"
      },
      {  
         "vegnr":"Ev39",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Liland",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1146",
         "long":"5.43723",
         "lat":"59.49436",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Ev39",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Fjøsangerveien",
         "autopass":"Ja",
         "takst_liten_bil":"19.0",
         "kommunenr":"1201",
         "long":"5.33814",
         "lat":"60.35241",
         "takst_stor_bil":"38.0"
      },
      {  
         "vegnr":"Ev39",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Nyebroen",
         "autopass":"Ja",
         "takst_liten_bil":"19.0",
         "kommunenr":"1201",
         "long":"5.33567",
         "lat":"60.37924",
         "takst_stor_bil":"38.0"
      },
      {  
         "vegnr":"Ev39",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Sandviken",
         "autopass":"Ja",
         "takst_liten_bil":"19.0",
         "kommunenr":"1201",
         "long":"5.31297",
         "lat":"60.41801",
         "takst_stor_bil":"38.0"
      },
      {  
         "vegnr":"Ev39",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Buvika (E39 Øysand)",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"1657",
         "long":"10.19487",
         "lat":"63.31115",
         "takst_stor_bil":"40.0"
      },
      {  
         "vegnr":"Ev39",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Fv.800 Thamshamn (Nord Litlsanda)",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"1657",
         "long":"9.89897",
         "lat":"63.32629",
         "takst_stor_bil":"40.0"
      },
      {  
         "vegnr":"Ev134",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Hodnafjell",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1146",
         "long":"5.48178",
         "lat":"59.46161",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Ev134",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Toskatjønn",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1106",
         "long":"5.34339",
         "lat":"59.41025",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Ev134",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Norheim",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1149",
         "long":"5.30327",
         "lat":"59.37697",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Ev134",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"E134 Åkrafjorden",
         "autopass":"Ja",
         "takst_liten_bil":"43.0",
         "kommunenr":"1211",
         "long":"6.35025",
         "lat":"59.85035",
         "takst_stor_bil":"86.0"
      },
      {  
         "vegnr":"Ev136",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Vågstranda bomstasjon",
         "autopass":"Ja",
         "takst_liten_bil":"42.0",
         "kommunenr":"1539",
         "long":"7.35116",
         "lat":"62.58553",
         "takst_stor_bil":"126.0"
      },
      {  
         "vegnr":"Ev136",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Vikebukt bomstasjon",
         "autopass":"Ja",
         "takst_liten_bil":"90.0",
         "kommunenr":"1535",
         "long":"7.14211",
         "lat":"62.61121",
         "takst_stor_bil":"270.0"
      },
      {  
         "vegnr":"Rv4",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Trondheimsveien",
         "autopass":"Ja",
         "takst_liten_bil":"32.0",
         "kommunenr":"0301",
         "long":"10.85250",
         "lat":"59.94787",
         "takst_stor_bil":"96.0"
      },
      {  
         "vegnr":"Rv7",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rv. 7 Brekkebygda",
         "autopass":"Ja",
         "takst_liten_bil":"70.0",
         "kommunenr":"0605",
         "long":"9.74950",
         "lat":"60.28603",
         "takst_stor_bil":"175.0"
      },
      {  
         "vegnr":"Rv9",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"rv9 Grim",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1001",
         "long":"7.98255",
         "lat":"58.14741",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Rv13",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rv.13 Hardangerbrua",
         "autopass":"Ja",
         "takst_liten_bil":"150.0",
         "kommunenr":"1231",
         "long":"6.83715",
         "lat":"60.47291",
         "takst_stor_bil":"600.0"
      },
      {  
         "vegnr":"Rv13",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rv 13 Svelgane",
         "autopass":"Ja",
         "takst_liten_bil":"43.0",
         "kommunenr":"1235",
         "long":"6.60547",
         "lat":"60.58787",
         "takst_stor_bil":"86.0"
      },
      {  
         "vegnr":"Rv19",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rv.19 Skoppum",
         "autopass":"Ja",
         "takst_liten_bil":"33.0",
         "kommunenr":"0701",
         "long":"10.39388",
         "lat":"59.37738",
         "takst_stor_bil":"66.0"
      },
      {  
         "vegnr":"Rv23",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rv. 23 Måna",
         "autopass":"Ja",
         "takst_liten_bil":"50.0",
         "kommunenr":"0215",
         "long":"10.65715",
         "lat":"59.69258",
         "takst_stor_bil":"125.0"
      },
      {  
         "vegnr":"Rv80",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rv 80 Strømsnes",
         "autopass":"Ja",
         "takst_liten_bil":"28.0",
         "kommunenr":"1841",
         "long":"15.19273",
         "lat":"67.29902",
         "takst_stor_bil":"56.0"
      },
      {  
         "vegnr":"Rv80",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rv 80 Vikan",
         "autopass":"Ja",
         "takst_liten_bil":"21.0",
         "kommunenr":"1804",
         "long":"14.70377",
         "lat":"67.30319",
         "takst_stor_bil":"42.0"
      },
      {  
         "vegnr":"Rv80",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Skjæringa",
         "autopass":"Ja",
         "takst_liten_bil":"15.0",
         "kommunenr":"1804",
         "long":"14.43648",
         "lat":"67.27712",
         "takst_stor_bil":"45.0"
      },
      {  
         "vegnr":"Rv80",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Jernbaneveien",
         "autopass":"Ja",
         "takst_liten_bil":"15.0",
         "kommunenr":"1804",
         "long":"14.39691",
         "lat":"67.28803",
         "takst_stor_bil":"45.0"
      },
      {  
         "vegnr":"Rv150",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Pårampe Granfoss fra Fornebu",
         "autopass":"Ja",
         "takst_liten_bil":"16.0",
         "kommunenr":"0219",
         "long":"10.62775",
         "lat":"59.90923",
         "takst_stor_bil":"48.0"
      },
      {  
         "vegnr":"Rv150",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Store Ringvei",
         "autopass":"Ja",
         "takst_liten_bil":"32.0",
         "kommunenr":"0301",
         "long":"10.72088",
         "lat":"59.94674",
         "takst_stor_bil":"96.0"
      },
      {  
         "vegnr":"Rv163",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Østre Aker vei",
         "autopass":"Ja",
         "takst_liten_bil":"32.0",
         "kommunenr":"0301",
         "long":"10.85177",
         "lat":"59.94015",
         "takst_stor_bil":"96.0"
      },
      {  
         "vegnr":"Rv509",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"RV510 SOLASPLITTEN",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"1124",
         "long":"5.66379",
         "lat":"58.89684",
         "takst_stor_bil":"50.0"
      },
      {  
         "vegnr":"Rv509",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"RV509 HAFRSFJORD",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"1103",
         "long":"5.61087",
         "lat":"58.96095",
         "takst_stor_bil":"50.0"
      },
      {  
         "vegnr":"Rv555",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Gravdal",
         "autopass":"Ja",
         "takst_liten_bil":"19.0",
         "kommunenr":"1201",
         "long":"5.26836",
         "lat":"60.38079",
         "takst_stor_bil":"38.0"
      },
      {  
         "vegnr":"Rv555",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Gyldenpris",
         "autopass":"Ja",
         "takst_liten_bil":"19.0",
         "kommunenr":"1201",
         "long":"5.31546",
         "lat":"60.38173",
         "takst_stor_bil":"38.0"
      },
      {  
         "vegnr":"Rv706",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Bjørndalen (Oslovn.) M-snitt)",
         "autopass":"Ja",
         "takst_liten_bil":"11.0",
         "kommunenr":"1601",
         "long":"10.38451",
         "lat":"63.39424",
         "takst_stor_bil":"22.0"
      },
      {  
         "vegnr":"Rv706",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rv 706 Leangensletta, O-snitt",
         "autopass":"Ja",
         "takst_liten_bil":"9.0",
         "kommunenr":"1601",
         "long":"10.47934",
         "lat":"63.43138",
         "takst_stor_bil":"27.0"
      },
      {  
         "vegnr":"Rv706",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Nord for Sluppen bru (Tempevn), M-snitt",
         "autopass":"Ja",
         "takst_liten_bil":"11.0",
         "kommunenr":"1601",
         "long":"10.38824",
         "lat":"63.39646",
         "takst_stor_bil":"22.0"
      },
      {  
         "vegnr":"Fv1",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Sødal",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1001",
         "long":"7.97220",
         "lat":"58.17536",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Fv2",
         "autopass_beskrivelse":"Kun manuell",
         "navn":"False",
         "autopass":"Nei",
         "takst_liten_bil":"False",
         "kommunenr":"0412",
         "long":"10.70762",
         "lat":"61.16445",
         "takst_stor_bil":"False"
      },
      {  
         "vegnr":"Fv7",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rv 7 Kjepsohøgda",
         "autopass":"Ja",
         "takst_liten_bil":"43.0",
         "kommunenr":"1238",
         "long":"6.48648",
         "lat":"60.44383",
         "takst_stor_bil":"86.0"
      },
      {  
         "vegnr":"Fv7",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Rv 7 Steinsdalen",
         "autopass":"Ja",
         "takst_liten_bil":"43.0",
         "kommunenr":"1238",
         "long":"6.07118",
         "lat":"60.36272",
         "takst_stor_bil":"86.0"
      },
      {  
         "vegnr":"Fv17",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Østbyen",
         "autopass":"Ja",
         "takst_liten_bil":"18.0",
         "kommunenr":"1703",
         "long":"11.52081",
         "lat":"64.46993",
         "takst_stor_bil":"36.0"
      },
      {  
         "vegnr":"Fv17",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Fv 17 Godøystraumen",
         "autopass":"Ja",
         "takst_liten_bil":"22.0",
         "kommunenr":"1804",
         "long":"14.71442",
         "lat":"67.24133",
         "takst_stor_bil":"44.0"
      },
      {  
         "vegnr":"Fv34",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Fv34 Grime",
         "autopass":"Ja",
         "takst_liten_bil":"27.0",
         "kommunenr":"0536",
         "long":"10.33270",
         "lat":"60.56063",
         "takst_stor_bil":"54.0"
      },
      {  
         "vegnr":"Fv43",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Fv.43 Kollevoll",
         "autopass":"Ja",
         "takst_liten_bil":"25.0",
         "kommunenr":"1032",
         "long":"6.94131",
         "lat":"58.11265",
         "takst_stor_bil":"50.0"
      },
      {  
         "vegnr":"Fv44",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"RV44 KÅSEN",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"1120",
         "long":"5.63792",
         "lat":"58.74219",
         "takst_stor_bil":"50.0"
      },
      {  
         "vegnr":"Fv44",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"RV44 ØKSNEVAD",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"1120",
         "long":"5.68040",
         "lat":"58.80359",
         "takst_stor_bil":"50.0"
      },
      {  
         "vegnr":"Fv44",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"RV44 FORUSVEIEN",
         "autopass":"Ja",
         "takst_liten_bil":"20.0",
         "kommunenr":"1103",
         "long":"5.73103",
         "lat":"58.88972",
         "takst_stor_bil":"50.0"
      },
      {  
         "vegnr":"Fv45",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Øvstabø",
         "autopass":"Ja",
         "takst_liten_bil":"48.0",
         "kommunenr":"1122",
         "long":"6.46540",
         "lat":"58.83026",
         "takst_stor_bil":"85.0"
      },
      {  
         "vegnr":"Fv47",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Liknes (Åkra sør)",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1149",
         "long":"5.19785",
         "lat":"59.23485",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Fv47",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Veakrossen",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1149",
         "long":"5.24761",
         "lat":"59.27731",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Fv47",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Bygnes",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1149",
         "long":"5.29211",
         "lat":"59.29835",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Fv47",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Karmsundsgata",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1106",
         "long":"5.29371",
         "lat":"59.39918",
         "takst_stor_bil":"28.0"
      },
      {  
         "vegnr":"Fv47",
         "autopass_beskrivelse":"AutoPASS + automatisk",
         "navn":"Tittelsnesvegen",
         "autopass":"Ja",
         "takst_liten_bil":"14.0",
         "kommunenr":"1106",
         "long":"5.26447",
         "lat":"59.42741",
         "takst_stor_bil":"28.0"
      }
   ],
   "page":1,
   "pages":3,
   "posts":210
};